name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    if: startsWith(github.event.head_commit.message, 'Releasing version') != true

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
            java-version: 16
            distribution: 'zulu'

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradlew') }}
          restore-keys: |
            ${{ runner.os }}-gradlew-

      - name: Build
        run: ./gradlew build

      - name: Show Reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
            name: reports-${{ runner.os }}
            if-no-files-found: ignore
            path: |
              build/reports/*
              api/build/reports/*
              app/build/reports/*
              app/cli/build/reports/*
              app/daemon/build/reports/*
              app/fx/build/reports/*
              client/build/reports/*
              core/build/reports/*
